### ISSUE TITLE
no data available leads to 'nan'-mails

### ISSUE THREAD

**Issue by goern** [thoth-station/slo-reporter#160]
**Describe the bug**
it seems like the backend metrics storage is not available, and slo reports get send out with a lot of nan and 0...

**Expected behavior**
nan-mails should not be sent, notification to alert should be raised.

**Screenshots**
![image](https://user-images.githubusercontent.com/260331/99779844-f59dd000-2b15-11eb-9d79-ac71eea6dcf2.png)

/kind bug
/priority important-soon

**Comment by pacospace** [comment]
Related to: https://github.com/thoth-station/slo-reporter/issues/157
