### ISSUE TITLE
Adjust endpoints for metrics in SLO reporter due to changes in metadata of Thoth Prometheus instances

### ISSUE THREAD

**Issue by pacospace** [thoth-station/slo-reporter#161]
**Describe the bug**
Changes in Prometheus: https://gitlab.cee.redhat.com/data-hub/dh-monitoring/-/merge_requests/358/diffs require some modifications in SLO reporter

**To Reproduce**

**Expected behavior**
All endpoints are adjusted to changes in Prometheus metadata, using only the instance in metadata.
**Screenshots**

**Additional context**

**Comment by goern** [comment]
@pacospace do you take care of this?

/kind bug

**Comment by pacospace** [comment]
> @pacospace do you take care of this?
> 
> /kind bug

Yes !
