### ISSUE TITLE
Create SLI for adviser quality and inputs stats

### ISSUE THREAD

**Issue by pacospace** [thoth-station/slo-reporter#248]
**Is your feature request related to a problem? Please describe.**
As Thoth Manager and Maintainer,

I want to see SLI on adviser quality.

**Describe the solution you'd like**

Include the following adviser quality SLI:

- [x] https://github.com/thoth-station/advise-reporter/issues/173
- [x] https://github.com/thoth-station/advise-reporter/issues/176 (https://github.com/thoth-station/advise-reporter/issues/169) 

**Describe alternatives you've considered**

**Additional context**

**Comment by goern** [comment]
/kind feature

@pacospace  are you going to work on this this sprint? -> lifecycle/active

**Comment by pacospace** [comment]
> /kind feature
> 
> @pacospace are you going to work on this this sprint? -> lifecycle/active

Yes it would be nice to have in this sprint I think
