### ISSUE TITLE
Add ‚change since last week‘ metrics

### ISSUE THREAD

**Issue by goern** [thoth-station/slo-reporter#32]
**Is your feature request related to a problem? Please describe.**
Add a ‚Change since last week‘ section to ‚Status of Thoth User-API‘, so that e we can see if we increase our user facing indicators

**Comment by bissenbay** [comment]
@goern Do you want add a column to the weekly email we get on Thoth SLI Metrics Report? If yes, what information do you want to see in there?

**Comment by goern** [comment]
@pacospace It looks to me like one more column per slo?!

**Comment by pacospace** [comment]
> @pacospace It looks to me like one more column per slo?!

Yes we can have another column, so every Friday we should see what happened that day and what changed respect to last week. I imagine something like
```
changes |  solvers |
  +1    |     7    |
```
