### ISSUE TITLE
Reporting on operated repos [5pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/slo-reporter#39]
As Thoth Product Owner,
I want to receive a weekly report via mail,
so that I can see the number of repos Kebechet operates,
and so that I can see the list of repo names

**Acceptance Criteria**

* mail is sent out weekly

**Comment by goern** [comment]
@pacospace @saisankargochhayat didnt you guys do that?

**Comment by pacospace** [comment]
> @pacospace @saisankargochhayat didnt you guys do that?

Yes you can see repos monitored by Kebechet and the increase per week. @goern

**Comment by pacospace** [comment]
```
Kebechet Info

Total active repositories | 162
Change in active repositories since last week | 22


```

**Comment by pacospace** [comment]
Do you want to see all names of the repos?

**Comment by saisankargochhayat** [comment]
> @pacospace @saisankargochhayat didnt you guys do that?

```
Total Kebechet Runs - x
Successful workflows - y
Failed workflows - z
```
@goern Should we get something like this?

**Comment by fridex** [comment]
I think the question was if this issue can be closed.



> ```
> Total Kebechet Runs - x
> Successful workflows - y
> Failed workflows - z
> ```
> 
> 
> @goern Should we get something like this?

I think it's good enough to have it on metrics side.

> Do you want to see all names of the repos?

I don't think this would be needed. We can query the database anytime.

**Comment by pacospace** [comment]
> I think the question was if this issue can be closed.
> 
> > ```
> > Total Kebechet Runs - x
> > Successful workflows - y
> > Failed workflows - z
> > ```
> > 
> > 
> > @goern Should we get something like this?
> 
> I think it's good enough to have it on metrics side.
> 
> > Do you want to see all names of the repos?
> 
> I don't think this would be needed. We can query the database anytime.

We have already successful percentage and average latency for all workflows :) 
```

Component | Succeeded
-- | --
adviser | 84.906 | %
kebechet | 74.783 | %
inspection | 12.5 | %
qeb-hwt | 90.041 | %
solver | 87.443 | %

Component | minutes | seconds
-- | -- | --
adviser | 2 | 31
kebechet | 5 | 48
inspection | 5 | 50
qeb-hwt | 1 | 31
solver | 8 | 10

```
