### ISSUE TITLE
SLO-reporter Release v0.6.0 BLOCKER

### ISSUE THREAD

**Issue by pacospace** [thoth-station/slo-reporter#78]
SLO-reporter features:
- [x] https://github.com/thoth-station/slo-reporter/issues/45

SLO-reporter new SLI features:

Thoth integrations SLI
- [x] https://github.com/thoth-station/slo-reporter/issues/81

SI SLI
- [x] https://github.com/thoth-station/slo-reporter/issues/82

Workflows (OPS):
- [x] https://github.com/thoth-station/slo-reporter/issues/79

Thoth Dashboards:
- [x] https://github.com/thoth-station/metrics-exporter/issues/476

**Comment by goern** [comment]
@pacospace shall we move all open issues to the next release?

**Comment by pacospace** [comment]
> @pacospace shall we move all open issues to the next release?

https://github.com/thoth-station/slo-reporter/issues/122
