### ISSUE TITLE
Create custom metrics for workflows so that we can monitor and alert on the status of our components. [3pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/slo-reporter#79]
Create custom metrics for workflows so that we can monitor and alert on the status of our components.

Some interesting ones:

* [ ] workflow/step durations
* [ ] step failure counters

Others:
* metrics derived from templates (e.g. model training score, error rate, etc.),
* any custom metric useful

References:
* https://argoproj.github.io/argo/metrics/

**Comment by goern** [comment]
@pacospace what do you think the complexity is? the amount of story points?

**Comment by pacospace** [comment]
I added 3 points, I created one to test for solver https://github.com/thoth-station/thoth-application/pull/367. But after discovering bug in Argo, we need to wait for new version of Argo to see metrics: https://github.com/thoth-station/thoth-application/issues/372
